[package]
name = "bbecs_tutorial"
version = "1.0.0"
edition = "2018"
description = "An ECS library made for a tutorial."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
thiserror = "1.0.26"