name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --release

